"""
Tests for centralized logging configuration module.

This module contains property-based tests to verify that the logging
configuration provides consistent formatting across all modules.
"""

import logging
import re
import tempfile
import os
from io import StringIO
from unittest.mock import patch
from hypothesis import given, strategies as st
import pytest

from apolo_11.src.logging_config import setup_logging, get_logger
from apolo_11.src.config import ConfigManager


class TestLoggingConfig:
    """Test cases for centralized logging configuration."""

    def test_setup_logging_with_default_config(self):
        """Test that setup_logging works with default configuration."""
        logger = setup_logging()
        assert logger is not None
        assert logger.name == 'apolo_11'
        assert logger.level == logging.INFO

    def test_get_logger_returns_proper_name(self):
        """Test that get_logger returns logger with proper naming."""
        logger = get_logger('test_module')
        assert logger.name == 'apolo_11.test_module'

    @given(st.text(min_size=1, max_size=50, alphabet=st.characters(whitelist_categories=('Lu', 'Ll', 'Nd'))))
    def test_property_logging_format_consistency(self, log_message):
        """
        Feature: apolo-11-improvements, Property 5: Formato de logging consistente
        Validates: Requirements 7.1
        
        For any log message generated by any module in the system, 
        the log format SHALL match the configured format pattern.
        """
        # Create a temporary config file with logging configuration
        with tempfile.NamedTemporaryFile(mode='w', suffix='.yaml', delete=False) as temp_config:
            temp_config.write("""
general:
  num_files_initial: 1
  num_files_final: 100
  time_cycle: 20

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

missions:
  codes:
    OrbitOne: ORBONE
  names:
    - OrbitOne

devices:
  status:
    - excellent
  types:
    - Satellite

date_format: "%d%m%y%H%M%S"

routes:
  - results: ./apolo_11/results
  - devices: ./apolo_11/results/devices
  - backups: ./apolo_11/results/backups/
  - reports: ./apolo_11/results/reports/
""")
            temp_config_path = temp_config.name

        try:
            # Setup logging with the temporary config
            logger = setup_logging(temp_config_path)
            
            # Create a string buffer to capture log output
            log_capture = StringIO()
            handler = logging.StreamHandler(log_capture)
            
            # Set the same format as configured
            formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
            handler.setFormatter(formatter)
            
            # Add handler to the logger
            logger.addHandler(handler)
            logger.setLevel(logging.INFO)
            
            # Log the test message
            logger.info(log_message)
            
            # Get the logged output
            log_output = log_capture.getvalue().strip()
            
            # Verify the format matches the expected pattern
            # Pattern: YYYY-MM-DD HH:MM:SS,mmm - logger_name - LEVEL - message
            expected_pattern = r'\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3} - apolo_11 - INFO - .*'
            
            assert re.match(expected_pattern, log_output), f"Log format doesn't match expected pattern. Got: {log_output}"
            
            # Verify the message is included in the output
            assert log_message in log_output, f"Log message '{log_message}' not found in output: {log_output}"
            
            # Clean up handler
            logger.removeHandler(handler)
            handler.close()
            
        finally:
            # Clean up temporary file
            os.unlink(temp_config_path)

    def test_logging_fallback_on_config_error(self):
        """Test that logging falls back to defaults when config fails."""
        # Test with non-existent config file
        logger = setup_logging('/non/existent/path.yaml')
        assert logger is not None
        assert logger.name == 'apolo_11'

    @given(st.sampled_from(['DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL']))
    def test_logging_level_configuration(self, log_level):
        """Test that logging level can be configured properly."""
        # Create a temporary config file with specific log level
        with tempfile.NamedTemporaryFile(mode='w', suffix='.yaml', delete=False) as temp_config:
            temp_config.write(f"""
logging:
  level: {log_level}
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

general:
  num_files_initial: 1
  num_files_final: 100
  time_cycle: 20

missions:
  codes:
    OrbitOne: ORBONE
  names:
    - OrbitOne

devices:
  status:
    - excellent
  types:
    - Satellite

date_format: "%d%m%y%H%M%S"

routes:
  - results: ./apolo_11/results
  - devices: ./apolo_11/results/devices
  - backups: ./apolo_11/results/backups/
  - reports: ./apolo_11/results/reports/
""")
            temp_config_path = temp_config.name

        try:
            logger = setup_logging(temp_config_path)
            expected_level = getattr(logging, log_level)
            assert logger.level == expected_level
            
        finally:
            os.unlink(temp_config_path)