general:
  num_files_initial: 1
  num_files_final: 100
  time_cycle: 20

missions:
  codes:
    OrbitOne: ORBONE
    ColonyMoon: CLNM
    VacMars: TMRS
    GalaxyTwo: GALXONE
  names:
    - OrbitOne
    - ColonyMoon
    - VacMars
    - GalaxyTwo
    - Moon'sBallon
devices:
  status:
    - excellent
    - good
    - warning
    - faulty
    - killed
    - unknown

  types:
    - Satellite
    - Spaceship
    - SpaceSuit
    - Rover
    - Equipment

date_format: "%d%m%y%H%M%S"

routes:
  - results: ./apolo_11/results
  - devices: ./apolo_11/results/devices
  - backups: ./apolo_11/results/backups/
  - reports: ./apolo_11/results/reports/
